apiVersion: serving.knative.dev/v1
kind: Route
metadata:
  name: lenet-route
spec:
  traffic:
  - configurationName: lenet
    percent: 100 
  - configurationName: nimblock-api-lenet
    percent: 0
  - configurationName: lenet2
    percent: 0
  - configurationName: nimblock-api-lenet2
    percent: 0

  
